# Generated by Django 3.2.6 on 2021-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('DatePosted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
